apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: blacklisted
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
    image: eu.gcr.io/bctf23/blacklisted-healthcheck:e98054bc67b6caeaa74be3742e7230e48ddf3aae97e40f0e43e871c9642143ba
  image: eu.gcr.io/bctf23/blacklisted-challenge:9d0460cd803fa5f773c6e37b87a012f5e31abaa224579b1cc4f2210645add7a1
