apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: majestic
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
    image: eu.gcr.io/bctf23/majestic-healthcheck:e98054bc67b6caeaa74be3742e7230e48ddf3aae97e40f0e43e871c9642143ba
  image: eu.gcr.io/bctf23/majestic-challenge:240cabe1b2a97de49de7ca1f2cbf2022a53497ca9c7531a86977d364fa5ed0ff
