[package]
name = "chicago"
version = "0.1.0"
authors = ["user"]
edition = "2018"
cargo-features = ["strip"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

