version: "3.7"
services:
    motd:
        container_name: motd
        build:
            dockerfile: ./deploy/Dockerfile
            context: ../
        logging:
            driver: "json-file"
        ports:
            - "1239:5000"
        cap_add:
            - SYS_ADMIN
        environment:
            - ADMIN_USER
            - ADMIN_PASS
            - FLAG