[package]
name = "kernel"
version = "0.1.0"
authors = ["Athryx <jack.x.roscoe@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-const-fn-init = "0.1.1"
volatile = "0.2.6"
spin = { version="0.9.2", features = ["mutex", "spin_mutex", "once"] }
concat-idents = "1.1.2"
bitflags = "1.2.1"
modular-bitfield = "0.11.2"
#either = { version = "1.6.1", default-features = false }
lazy_static = { version = "1.0", features = ["spin_no_std"] }
siphasher = "0.3.10"
arrayvec = { version = "0.7.2", default-features = false }
uart_16550 = "0.2.18"
# bit_utils = { path = "../lib/bit_utils" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true

[package.metadata.cargo-sysroot]
target = "x86_64-os-kernel.json"
